export enum ActionType {
  AUTH_START = 'AUTH_START',
  AUTH_SUCCESS = 'AUTH_SUCCESS',
  AUTH_FAIL = 'AUTH_FAIL',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
  CHECK_AUTH_TIMEOUT = 'CHECK_AUTH_TIMEOUT',
  SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH',
}
